// <auto-generated />
using AquaDex.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AquaDex.Infrastructure.Migrations
{
    [DbContext(typeof(AquaDexDbContext))]
    [Migration("20260709173310_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AquaDex.Core.Entities.Species", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BestBaitTechnique")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommonNameAz")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommonNameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConservationStatus")
                        .HasColumnType("int");

                    b.Property<string>("Diet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HabitatType")
                        .HasColumnType("int");

                    b.Property<string>("LatinName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegalSeasonNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MaxSizeCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinSizeCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Species");
                });

            modelBuilder.Entity("AquaDex.Core.Entities.SpeciesWaterbody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AbundanceRating")
                        .HasColumnType("int");

                    b.Property<string>("SeasonNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SpeciesId")
                        .HasColumnType("int");

                    b.Property<int>("WaterbodyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WaterbodyId");

                    b.HasIndex("SpeciesId", "WaterbodyId")
                        .IsUnique();

                    b.ToTable("SpeciesWaterbodies");
                });

            modelBuilder.Entity("AquaDex.Core.Entities.Waterbody", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Waterbodies");
                });

            modelBuilder.Entity("AquaDex.Core.Entities.SpeciesWaterbody", b =>
                {
                    b.HasOne("AquaDex.Core.Entities.Species", "Species")
                        .WithMany("SpeciesWaterbodies")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AquaDex.Core.Entities.Waterbody", "Waterbody")
                        .WithMany("SpeciesWaterbodies")
                        .HasForeignKey("WaterbodyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Species");

                    b.Navigation("Waterbody");
                });

            modelBuilder.Entity("AquaDex.Core.Entities.Species", b =>
                {
                    b.Navigation("SpeciesWaterbodies");
                });

            modelBuilder.Entity("AquaDex.Core.Entities.Waterbody", b =>
                {
                    b.Navigation("SpeciesWaterbodies");
                });
#pragma warning restore 612, 618
        }
    }
}
